import { Noticia_Text } from "next/font/google";
import "../styles/globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Footer from "@/components/Footer";
const noticia = Noticia_Text({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "700"],
  variable: "--font-noticia",
});
export const metadata = {
  title: "GalsPress",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={noticia.className}>{children}</body>
    </html>
  );
}
